// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`

/// The active Sequentia network's identifier, e.g. `"sequentia-testnet"`.
String networkName() => RustLib.instance.api.crateApiNetworkName();

/// Generate a fresh 12-word BIP39 recovery phrase.
Future<String> generateMnemonic() =>
    RustLib.instance.api.crateApiGenerateMnemonic();

/// The default (non-confidential, Bitcoin-format `tb1…`) receive address for a
/// recovery phrase, at index 0. The same address also receives on Bitcoin
/// testnet4 — one address, both chains.
Future<String> receiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiReceiveAddress(mnemonic: mnemonic);

/// The opt-in confidential ("private", blech32 `tsqb…`) receive address at
/// index 0. NOT Bitcoin-compatible (it embeds a blinding key).
Future<String> confidentialReceiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiConfidentialReceiveAddress(mnemonic: mnemonic);

/// The wallet's CT output descriptor for a recovery phrase.
Future<String> descriptorFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiDescriptorFromMnemonic(mnemonic: mnemonic);

/// Validate a BIP39 recovery phrase (import flow). Throws on an invalid phrase.
Future<void> validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiValidateMnemonic(mnemonic: mnemonic);

/// Receive address at `index`: non-confidential `tb1…` (default) or the opt-in
/// confidential `tsqb…` form. Returns the address + the index it used.
Future<AddressInfo> receiveAddressAt({
  required String mnemonic,
  required int index,
  required bool confidential,
}) => RustLib.instance.api.crateApiReceiveAddressAt(
  mnemonic: mnemonic,
  index: index,
  confidential: confidential,
);

/// A receive address together with the derivation index it came from.
class AddressInfo {
  final String address;
  final int index;

  const AddressInfo({required this.address, required this.index});

  @override
  int get hashCode => address.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index;
}
