// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `rerr`

/// The active Sequentia network's identifier, e.g. `"sequentia-testnet"`.
String networkName() => RustLib.instance.api.crateApiNetworkName();

/// Generate a fresh 12-word BIP39 recovery phrase.
Future<String> generateMnemonic() =>
    RustLib.instance.api.crateApiGenerateMnemonic();

/// The default (non-confidential, Bitcoin-format `tb1…`) receive address for a
/// recovery phrase, at index 0. The same address also receives on Bitcoin
/// testnet4 — one address, both chains.
Future<String> receiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiReceiveAddress(mnemonic: mnemonic);

/// The opt-in confidential ("private", blech32 `tsqb…`) receive address at
/// index 0. NOT Bitcoin-compatible (it embeds a blinding key).
Future<String> confidentialReceiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiConfidentialReceiveAddress(mnemonic: mnemonic);

/// The wallet's CT output descriptor for a recovery phrase.
Future<String> descriptorFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiDescriptorFromMnemonic(mnemonic: mnemonic);

/// Validate a BIP39 recovery phrase (import flow). Throws on an invalid phrase.
Future<void> validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiValidateMnemonic(mnemonic: mnemonic);

/// Receive address at `index`: non-confidential `tb1…` (default) or the opt-in
/// confidential `tsqb…` form. Returns the address + the index it used.
Future<AddressInfo> receiveAddressAt({
  required String mnemonic,
  required int index,
  required bool confidential,
}) => RustLib.instance.api.crateApiReceiveAddressAt(
  mnemonic: mnemonic,
  index: index,
  confidential: confidential,
);

/// Full-scan the wallet against `esplora_url`, apply the update, and return the
/// chain tip, per-asset balances, and the next unused receive index. Runs on an
/// FRB worker thread (off the UI thread).
Future<WalletSync> syncWallet({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiSyncWallet(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// Quick format-level validity check of a recipient address.
Future<void> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiValidateAddress(address: address);

/// Build an UNSIGNED send PSET (base64). Syncs first so the wallet has utxos.
/// `fee_asset` pays the fee in a non-native asset at the EXACT published rate
/// (never fabricated); `fee_rate_sat_kvb` None = builder default. RBF is on by
/// default (so a stuck tx can be bump/CPFP-rescued later).
Future<String> buildSendTx({
  required String mnemonic,
  required String esploraUrl,
  required List<Recipient> recipients,
  double? feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildSendTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  recipients: recipients,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// Sign a PSET with the software signer (mnemonic read transiently, never
/// cached). Returns the signed PSET as base64.
Future<String> signPset({required String mnemonic, required String pset}) =>
    RustLib.instance.api.crateApiSignPset(mnemonic: mnemonic, pset: pset);

/// Finalize a signed PSET into a transaction and broadcast it. Returns the txid.
Future<String> finalizeAndBroadcast({
  required String mnemonic,
  required String esploraUrl,
  required String pset,
}) => RustLib.instance.api.crateApiFinalizeAndBroadcast(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  pset: pset,
);

/// Sync and return the wallet's transaction history (net signed per-asset deltas
/// per tx). Ordering is left to the UI.
Future<List<TxRow>> walletTransactions({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiWalletTransactions(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// A receive address together with the derivation index it came from.
class AddressInfo {
  final String address;
  final int index;

  const AddressInfo({required this.address, required this.index});

  @override
  int get hashCode => address.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index;
}

/// A per-asset balance: the asset id (hex) and the amount in atoms (a string to
/// avoid any integer-precision loss across the FFI boundary).
class AssetBalance {
  final String assetId;
  final String atoms;

  const AssetBalance({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetBalance &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// A signed per-asset delta on a transaction (atoms as a string; may be negative).
class AssetDelta {
  final String assetId;
  final String atoms;

  const AssetDelta({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetDelta &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// Pay the fee in a non-native asset at the node's published rate.
class FeeAsset {
  final String assetId;
  final BigInt rate;

  const FeeAsset({required this.assetId, required this.rate});

  @override
  int get hashCode => assetId.hashCode ^ rate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeeAsset &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          rate == other.rate;
}

/// A send recipient: who, which asset, how many atoms.
class Recipient {
  final String address;
  final String assetId;
  final BigInt satoshi;

  const Recipient({
    required this.address,
    required this.assetId,
    required this.satoshi,
  });

  @override
  int get hashCode => address.hashCode ^ assetId.hashCode ^ satoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recipient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          assetId == other.assetId &&
          satoshi == other.satoshi;
}

/// A wallet transaction history row.
class TxRow {
  final String txid;
  final int? height;
  final BigInt? timestamp;

  /// "incoming" | "outgoing" | "issuance" | "reissuance" | "burn" | "redeposit" | "unknown".
  final String kind;
  final BigInt fee;
  final List<AssetDelta> deltas;

  const TxRow({
    required this.txid,
    this.height,
    this.timestamp,
    required this.kind,
    required this.fee,
    required this.deltas,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      timestamp.hashCode ^
      kind.hashCode ^
      fee.hashCode ^
      deltas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxRow &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          timestamp == other.timestamp &&
          kind == other.kind &&
          fee == other.fee &&
          deltas == other.deltas;
}

/// A snapshot of the wallet after a full scan against an esplora backend.
class WalletSync {
  final int tipHeight;
  final String tipHash;
  final List<AssetBalance> balances;
  final int nextIndex;

  const WalletSync({
    required this.tipHeight,
    required this.tipHash,
    required this.balances,
    required this.nextIndex,
  });

  @override
  int get hashCode =>
      tipHeight.hashCode ^
      tipHash.hashCode ^
      balances.hashCode ^
      nextIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSync &&
          runtimeType == other.runtimeType &&
          tipHeight == other.tipHeight &&
          tipHash == other.tipHash &&
          balances == other.balances &&
          nextIndex == other.nextIndex;
}
