// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_fee_and_finish`, `err`, `esplora_client`, `rerr`, `with_synced_wollet`, `wollet_cache`

/// The active Sequentia network's identifier, e.g. `"sequentia-testnet"`.
String networkName() => RustLib.instance.api.crateApiNetworkName();

/// Point wallet persistence at the app's writable directory. Call once at
/// startup, before any sync, so cold starts resume scanned state from disk
/// instead of re-scanning the whole wallet.
void setDataDir({required String path}) =>
    RustLib.instance.api.crateApiSetDataDir(path: path);

/// Set the `Authorization` header for a node behind HTTP auth (a bearer token or
/// basic-auth credentials). Pass an empty string to clear it. Applied to every
/// Esplora request; call whenever the node or its credentials change.
void setAuthHeader({required String value}) =>
    RustLib.instance.api.crateApiSetAuthHeader(value: value);

/// Generate a fresh 12-word BIP39 recovery phrase.
Future<String> generateMnemonic() =>
    RustLib.instance.api.crateApiGenerateMnemonic();

/// The default (non-confidential, Bitcoin-format `tb1…`) receive address for a
/// recovery phrase, at index 0. The same address also receives on Bitcoin
/// testnet4 — one address, both chains.
Future<String> receiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiReceiveAddress(mnemonic: mnemonic);

/// The opt-in confidential ("private", blech32 `tsqb…`) receive address at
/// index 0. NOT Bitcoin-compatible (it embeds a blinding key).
Future<String> confidentialReceiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiConfidentialReceiveAddress(mnemonic: mnemonic);

/// The wallet's CT output descriptor for a recovery phrase.
Future<String> descriptorFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiDescriptorFromMnemonic(mnemonic: mnemonic);

/// Validate a BIP39 recovery phrase (import flow). Throws on an invalid phrase.
Future<void> validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiValidateMnemonic(mnemonic: mnemonic);

/// Receive address at `index`: non-confidential `tb1…` (default) or the opt-in
/// confidential `tsqb…` form. Returns the address + the index it used.
Future<AddressInfo> receiveAddressAt({
  required String mnemonic,
  required int index,
  required bool confidential,
}) => RustLib.instance.api.crateApiReceiveAddressAt(
  mnemonic: mnemonic,
  index: index,
  confidential: confidential,
);

/// Full-scan the wallet against `esplora_url`, apply the update, and return the
/// chain tip, per-asset balances, and the next unused receive index. Runs on an
/// FRB worker thread (off the UI thread).
Future<WalletSync> syncWallet({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiSyncWallet(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// Validate a recipient address is a well-formed **Sequentia** address (rejects
/// foreign-network addresses).
Future<void> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiValidateAddress(address: address);

/// Build an UNSIGNED send PSET (base64). Syncs first so the wallet has utxos.
/// `fee_asset` pays the fee in any accepted asset at the EXACT published rate
/// (never fabricated); `fee_rate_sat_kvb` None = builder default. RBF is on by
/// default (so a stuck tx can be bump/CPFP-rescued later).
Future<String> buildSendTx({
  required String mnemonic,
  required String esploraUrl,
  required List<Recipient> recipients,
  double? feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildSendTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  recipients: recipients,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// Sign a PSET with the software signer (mnemonic read transiently, never
/// cached). Returns the signed PSET as base64.
Future<String> signPset({required String mnemonic, required String pset}) =>
    RustLib.instance.api.crateApiSignPset(mnemonic: mnemonic, pset: pset);

/// Finalize a signed PSET into a transaction and broadcast it. Returns the txid.
Future<String> finalizeAndBroadcast({
  required String mnemonic,
  required String esploraUrl,
  required String pset,
}) => RustLib.instance.api.crateApiFinalizeAndBroadcast(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  pset: pset,
);

/// Sync and return the wallet's transaction history (net signed per-asset deltas
/// per tx). Ordering is left to the UI.
Future<List<TxRow>> walletTransactions({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiWalletTransactions(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// Forget any cached wallet state (called when the wallet is removed).
Future<void> clearWalletCache() =>
    RustLib.instance.api.crateApiClearWalletCache();

/// RBF fee-bump: re-send the SAME payment at a higher fee (optionally in another
/// asset). The replacement's reference (rfa) fee must exceed the original's.
Future<String> buildRbfBumpTx({
  required String mnemonic,
  required String esploraUrl,
  required String txid,
  required double feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildRbfBumpTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  txid: txid,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// RBF replace: same inputs, brand-new recipients — to correct a still-pending
/// payment's address/asset/amount.
Future<String> buildRbfReplaceTx({
  required String mnemonic,
  required String esploraUrl,
  required String txid,
  required List<Recipient> newRecipients,
  required double feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildRbfReplaceTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  txid: txid,
  newRecipients: newRecipients,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// CPFP: a child that spends the parent's unconfirmed wallet output and pays a
/// high fee (in any accepted asset) to lift the {parent, child} package.
Future<String> buildCpfpTx({
  required String mnemonic,
  required String esploraUrl,
  required String parentTxid,
  required double feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildCpfpTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  parentTxid: parentTxid,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// A conservative child fee rate (sat/kvb) that lifts the {parent, child}
/// package to `target_feerate`.
Future<double> cpfpSuggestedFeerate({
  required String mnemonic,
  required String esploraUrl,
  required String parentTxid,
  required double targetFeerate,
}) => RustLib.instance.api.crateApiCpfpSuggestedFeerate(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  parentTxid: parentTxid,
  targetFeerate: targetFeerate,
);

/// Issue a brand-new asset: mint `asset_sats` of it plus `token_sats` reissuance
/// tokens, both to this wallet. The new asset's id appears after the tx
/// confirms and the wallet re-syncs.
Future<String> buildIssueTx({
  required String mnemonic,
  required String esploraUrl,
  required BigInt assetSats,
  required BigInt tokenSats,
  double? feeRateSatKvb,
}) => RustLib.instance.api.crateApiBuildIssueTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  assetSats: assetSats,
  tokenSats: tokenSats,
  feeRateSatKvb: feeRateSatKvb,
);

/// Reissue more of an existing asset (needs its reissuance token in this wallet).
Future<String> buildReissueTx({
  required String mnemonic,
  required String esploraUrl,
  required String assetId,
  required BigInt satoshi,
  double? feeRateSatKvb,
}) => RustLib.instance.api.crateApiBuildReissueTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  assetId: assetId,
  satoshi: satoshi,
  feeRateSatKvb: feeRateSatKvb,
);

/// Permanently destroy `satoshi` atoms of an asset.
Future<String> buildBurnTx({
  required String mnemonic,
  required String esploraUrl,
  required String assetId,
  required BigInt satoshi,
  double? feeRateSatKvb,
}) => RustLib.instance.api.crateApiBuildBurnTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  assetId: assetId,
  satoshi: satoshi,
  feeRateSatKvb: feeRateSatKvb,
);

/// The 33-byte staker public key (compressed hex) at m/2/0 — the key a stake is
/// bonded to (the wallet controls the matching private key to later unbond).
Future<String> stakerPublicKey({required String mnemonic}) =>
    RustLib.instance.api.crateApiStakerPublicKey(mnemonic: mnemonic);

/// Bond `satoshi` atoms of tSEQ into the canonical CSV-locked staking script for
/// `staker_pubkey` (33-byte hex). Enforces the 40,000-tSEQ minimum. The output
/// is non-confidential (only explicit stake confers weight).
Future<String> buildStakeTx({
  required String mnemonic,
  required String esploraUrl,
  required String stakerPubkey,
  required int csv,
  required BigInt satoshi,
  double? feeRateSatKvb,
}) => RustLib.instance.api.crateApiBuildStakeTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  stakerPubkey: stakerPubkey,
  csv: csv,
  satoshi: satoshi,
  feeRateSatKvb: feeRateSatKvb,
);

/// A receive address together with the derivation index it came from.
class AddressInfo {
  final String address;
  final int index;

  const AddressInfo({required this.address, required this.index});

  @override
  int get hashCode => address.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index;
}

/// A per-asset balance: the asset id (hex) and the amount in atoms (a string to
/// avoid any integer-precision loss across the FFI boundary).
class AssetBalance {
  final String assetId;
  final String atoms;

  const AssetBalance({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetBalance &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// A signed per-asset delta on a transaction (atoms as a string; may be negative).
class AssetDelta {
  final String assetId;
  final String atoms;

  const AssetDelta({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetDelta &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// Pay the fee in any accepted asset at the node's published rate.
class FeeAsset {
  final String assetId;
  final BigInt rate;

  const FeeAsset({required this.assetId, required this.rate});

  @override
  int get hashCode => assetId.hashCode ^ rate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeeAsset &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          rate == other.rate;
}

/// A send recipient: who, which asset, how many atoms.
class Recipient {
  final String address;
  final String assetId;
  final BigInt satoshi;

  const Recipient({
    required this.address,
    required this.assetId,
    required this.satoshi,
  });

  @override
  int get hashCode => address.hashCode ^ assetId.hashCode ^ satoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recipient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          assetId == other.assetId &&
          satoshi == other.satoshi;
}

/// A wallet transaction history row.
class TxRow {
  final String txid;
  final int? height;
  final BigInt? timestamp;

  /// "incoming" | "outgoing" | "issuance" | "reissuance" | "burn" | "redeposit" | "unknown".
  final String kind;
  final BigInt fee;
  final List<AssetDelta> deltas;

  const TxRow({
    required this.txid,
    this.height,
    this.timestamp,
    required this.kind,
    required this.fee,
    required this.deltas,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      timestamp.hashCode ^
      kind.hashCode ^
      fee.hashCode ^
      deltas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxRow &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          timestamp == other.timestamp &&
          kind == other.kind &&
          fee == other.fee &&
          deltas == other.deltas;
}

/// A snapshot of the wallet after a full scan against an esplora backend.
class WalletSync {
  final int tipHeight;
  final String tipHash;
  final List<AssetBalance> balances;
  final int nextIndex;

  const WalletSync({
    required this.tipHeight,
    required this.tipHash,
    required this.balances,
    required this.nextIndex,
  });

  @override
  int get hashCode =>
      tipHeight.hashCode ^
      tipHash.hashCode ^
      balances.hashCode ^
      nextIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSync &&
          runtimeType == other.runtimeType &&
          tipHeight == other.tipHeight &&
          tipHash == other.tipHash &&
          balances == other.balances &&
          nextIndex == other.nextIndex;
}
