// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressInfo dco_decode_address_info(dynamic raw);

  @protected
  AssetBalance dco_decode_asset_balance(dynamic raw);

  @protected
  AssetDelta dco_decode_asset_delta(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  FeeAsset dco_decode_box_autoadd_fee_asset(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BtcBalance dco_decode_btc_balance(dynamic raw);

  @protected
  BtcTx dco_decode_btc_tx(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeeAsset dco_decode_fee_asset(dynamic raw);

  @protected
  List<AssetBalance> dco_decode_list_asset_balance(dynamic raw);

  @protected
  List<AssetDelta> dco_decode_list_asset_delta(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Recipient> dco_decode_list_recipient(dynamic raw);

  @protected
  List<TxRow> dco_decode_list_tx_row(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  FeeAsset? dco_decode_opt_box_autoadd_fee_asset(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PsetFee dco_decode_pset_fee(dynamic raw);

  @protected
  Recipient dco_decode_recipient(dynamic raw);

  @protected
  SeqdexSwapRequestOut dco_decode_seqdex_swap_request_out(dynamic raw);

  @protected
  TxRow dco_decode_tx_row(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WalletSync dco_decode_wallet_sync(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressInfo sse_decode_address_info(SseDeserializer deserializer);

  @protected
  AssetBalance sse_decode_asset_balance(SseDeserializer deserializer);

  @protected
  AssetDelta sse_decode_asset_delta(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  FeeAsset sse_decode_box_autoadd_fee_asset(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BtcBalance sse_decode_btc_balance(SseDeserializer deserializer);

  @protected
  BtcTx sse_decode_btc_tx(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeeAsset sse_decode_fee_asset(SseDeserializer deserializer);

  @protected
  List<AssetBalance> sse_decode_list_asset_balance(
    SseDeserializer deserializer,
  );

  @protected
  List<AssetDelta> sse_decode_list_asset_delta(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Recipient> sse_decode_list_recipient(SseDeserializer deserializer);

  @protected
  List<TxRow> sse_decode_list_tx_row(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  FeeAsset? sse_decode_opt_box_autoadd_fee_asset(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PsetFee sse_decode_pset_fee(SseDeserializer deserializer);

  @protected
  Recipient sse_decode_recipient(SseDeserializer deserializer);

  @protected
  SeqdexSwapRequestOut sse_decode_seqdex_swap_request_out(
    SseDeserializer deserializer,
  );

  @protected
  TxRow sse_decode_tx_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WalletSync sse_decode_wallet_sync(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_info(AddressInfo self, SseSerializer serializer);

  @protected
  void sse_encode_asset_balance(AssetBalance self, SseSerializer serializer);

  @protected
  void sse_encode_asset_delta(AssetDelta self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fee_asset(
    FeeAsset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_btc_balance(BtcBalance self, SseSerializer serializer);

  @protected
  void sse_encode_btc_tx(BtcTx self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fee_asset(FeeAsset self, SseSerializer serializer);

  @protected
  void sse_encode_list_asset_balance(
    List<AssetBalance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_asset_delta(
    List<AssetDelta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recipient(
    List<Recipient> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tx_row(List<TxRow> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fee_asset(
    FeeAsset? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pset_fee(PsetFee self, SseSerializer serializer);

  @protected
  void sse_encode_recipient(Recipient self, SseSerializer serializer);

  @protected
  void sse_encode_seqdex_swap_request_out(
    SeqdexSwapRequestOut self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tx_row(TxRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_sync(WalletSync self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
