// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -403299103;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ambra_core',
        ioDirectory: '../ambra_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiBtcBroadcast({
    required String t4Api,
    required String txHex,
  });

  Future<BtcTx> crateApiBtcPrepare({
    required String mnemonic,
    required String t4Api,
    required String address,
    required BigInt amountSats,
    required double feeRate,
  });

  Future<BtcBalance> crateApiBtcSync({
    required String mnemonic,
    required String t4Api,
  });

  Future<String> crateApiBuildBurnTx({
    required String mnemonic,
    required String esploraUrl,
    required String assetId,
    required BigInt satoshi,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<String> crateApiBuildCpfpTx({
    required String mnemonic,
    required String esploraUrl,
    required String parentTxid,
    required double feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<String> crateApiBuildIssueTx({
    required String mnemonic,
    required String esploraUrl,
    required BigInt assetSats,
    required BigInt tokenSats,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<String> crateApiBuildRbfBumpTx({
    required String mnemonic,
    required String esploraUrl,
    required String txid,
    required double feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<String> crateApiBuildRbfReplaceTx({
    required String mnemonic,
    required String esploraUrl,
    required String txid,
    required List<Recipient> newRecipients,
    required double feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<String> crateApiBuildReissueTx({
    required String mnemonic,
    required String esploraUrl,
    required String assetId,
    required BigInt satoshi,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<String> crateApiBuildSendTx({
    required String mnemonic,
    required String esploraUrl,
    required List<Recipient> recipients,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<String> crateApiBuildStakeTx({
    required String mnemonic,
    required String esploraUrl,
    required String stakerPubkey,
    required int csv,
    required BigInt satoshi,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  });

  Future<void> crateApiClearWalletCache();

  Future<String> crateApiConfidentialReceiveAddress({required String mnemonic});

  Future<double> crateApiCpfpSuggestedFeerate({
    required String mnemonic,
    required String esploraUrl,
    required String parentTxid,
    required double targetFeerate,
  });

  Future<String> crateApiDescriptorFromMnemonic({required String mnemonic});

  Future<String> crateApiFinalizeAndBroadcast({
    required String mnemonic,
    required String esploraUrl,
    required String pset,
  });

  Future<String> crateApiGenerateMnemonic();

  String crateApiNetworkName();

  Future<PsetFee> crateApiPsetFee({required String pset});

  Future<String> crateApiReceiveAddress({required String mnemonic});

  Future<AddressInfo> crateApiReceiveAddressAt({
    required String mnemonic,
    required int index,
    required bool confidential,
  });

  Future<SeqdexSwapRequestOut> crateApiSeqdexBuildSwapRequest({
    required String mnemonic,
    required String esploraUrl,
    required String assetP,
    required BigInt amountP,
    required String assetR,
    required BigInt amountR,
    required String feeAsset,
    required BigInt feeAmount,
  });

  Future<String> crateApiSeqdexSignAccept({
    required String mnemonic,
    required String esploraUrl,
    required String acceptPset,
  });

  void crateApiSetAuthHeader({required String value});

  void crateApiSetDataDir({required String path});

  Future<String> crateApiSignPset({
    required String mnemonic,
    required String pset,
  });

  Future<String> crateApiStakerPublicKey({required String mnemonic});

  Future<WalletSync> crateApiSyncWallet({
    required String mnemonic,
    required String esploraUrl,
  });

  Future<void> crateApiValidateAddress({required String address});

  Future<void> crateApiValidateMnemonic({required String mnemonic});

  Future<List<TxRow>> crateApiWalletTransactions({
    required String mnemonic,
    required String esploraUrl,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiBtcBroadcast({
    required String t4Api,
    required String txHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(t4Api, serializer);
          sse_encode_String(txHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBtcBroadcastConstMeta,
        argValues: [t4Api, txHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBtcBroadcastConstMeta => const TaskConstMeta(
    debugName: "btc_broadcast",
    argNames: ["t4Api", "txHex"],
  );

  @override
  Future<BtcTx> crateApiBtcPrepare({
    required String mnemonic,
    required String t4Api,
    required String address,
    required BigInt amountSats,
    required double feeRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(t4Api, serializer);
          sse_encode_String(address, serializer);
          sse_encode_u_64(amountSats, serializer);
          sse_encode_f_64(feeRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_btc_tx,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBtcPrepareConstMeta,
        argValues: [mnemonic, t4Api, address, amountSats, feeRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBtcPrepareConstMeta => const TaskConstMeta(
    debugName: "btc_prepare",
    argNames: ["mnemonic", "t4Api", "address", "amountSats", "feeRate"],
  );

  @override
  Future<BtcBalance> crateApiBtcSync({
    required String mnemonic,
    required String t4Api,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(t4Api, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_btc_balance,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBtcSyncConstMeta,
        argValues: [mnemonic, t4Api],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBtcSyncConstMeta => const TaskConstMeta(
    debugName: "btc_sync",
    argNames: ["mnemonic", "t4Api"],
  );

  @override
  Future<String> crateApiBuildBurnTx({
    required String mnemonic,
    required String esploraUrl,
    required String assetId,
    required BigInt satoshi,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(assetId, serializer);
          sse_encode_u_64(satoshi, serializer);
          sse_encode_opt_box_autoadd_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildBurnTxConstMeta,
        argValues: [
          mnemonic,
          esploraUrl,
          assetId,
          satoshi,
          feeRateSatKvb,
          feeAsset,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildBurnTxConstMeta => const TaskConstMeta(
    debugName: "build_burn_tx",
    argNames: [
      "mnemonic",
      "esploraUrl",
      "assetId",
      "satoshi",
      "feeRateSatKvb",
      "feeAsset",
    ],
  );

  @override
  Future<String> crateApiBuildCpfpTx({
    required String mnemonic,
    required String esploraUrl,
    required String parentTxid,
    required double feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(parentTxid, serializer);
          sse_encode_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildCpfpTxConstMeta,
        argValues: [mnemonic, esploraUrl, parentTxid, feeRateSatKvb, feeAsset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildCpfpTxConstMeta => const TaskConstMeta(
    debugName: "build_cpfp_tx",
    argNames: [
      "mnemonic",
      "esploraUrl",
      "parentTxid",
      "feeRateSatKvb",
      "feeAsset",
    ],
  );

  @override
  Future<String> crateApiBuildIssueTx({
    required String mnemonic,
    required String esploraUrl,
    required BigInt assetSats,
    required BigInt tokenSats,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_u_64(assetSats, serializer);
          sse_encode_u_64(tokenSats, serializer);
          sse_encode_opt_box_autoadd_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildIssueTxConstMeta,
        argValues: [
          mnemonic,
          esploraUrl,
          assetSats,
          tokenSats,
          feeRateSatKvb,
          feeAsset,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildIssueTxConstMeta => const TaskConstMeta(
    debugName: "build_issue_tx",
    argNames: [
      "mnemonic",
      "esploraUrl",
      "assetSats",
      "tokenSats",
      "feeRateSatKvb",
      "feeAsset",
    ],
  );

  @override
  Future<String> crateApiBuildRbfBumpTx({
    required String mnemonic,
    required String esploraUrl,
    required String txid,
    required double feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(txid, serializer);
          sse_encode_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildRbfBumpTxConstMeta,
        argValues: [mnemonic, esploraUrl, txid, feeRateSatKvb, feeAsset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildRbfBumpTxConstMeta => const TaskConstMeta(
    debugName: "build_rbf_bump_tx",
    argNames: ["mnemonic", "esploraUrl", "txid", "feeRateSatKvb", "feeAsset"],
  );

  @override
  Future<String> crateApiBuildRbfReplaceTx({
    required String mnemonic,
    required String esploraUrl,
    required String txid,
    required List<Recipient> newRecipients,
    required double feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(txid, serializer);
          sse_encode_list_recipient(newRecipients, serializer);
          sse_encode_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildRbfReplaceTxConstMeta,
        argValues: [
          mnemonic,
          esploraUrl,
          txid,
          newRecipients,
          feeRateSatKvb,
          feeAsset,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildRbfReplaceTxConstMeta => const TaskConstMeta(
    debugName: "build_rbf_replace_tx",
    argNames: [
      "mnemonic",
      "esploraUrl",
      "txid",
      "newRecipients",
      "feeRateSatKvb",
      "feeAsset",
    ],
  );

  @override
  Future<String> crateApiBuildReissueTx({
    required String mnemonic,
    required String esploraUrl,
    required String assetId,
    required BigInt satoshi,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(assetId, serializer);
          sse_encode_u_64(satoshi, serializer);
          sse_encode_opt_box_autoadd_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildReissueTxConstMeta,
        argValues: [
          mnemonic,
          esploraUrl,
          assetId,
          satoshi,
          feeRateSatKvb,
          feeAsset,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildReissueTxConstMeta => const TaskConstMeta(
    debugName: "build_reissue_tx",
    argNames: [
      "mnemonic",
      "esploraUrl",
      "assetId",
      "satoshi",
      "feeRateSatKvb",
      "feeAsset",
    ],
  );

  @override
  Future<String> crateApiBuildSendTx({
    required String mnemonic,
    required String esploraUrl,
    required List<Recipient> recipients,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_list_recipient(recipients, serializer);
          sse_encode_opt_box_autoadd_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildSendTxConstMeta,
        argValues: [mnemonic, esploraUrl, recipients, feeRateSatKvb, feeAsset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildSendTxConstMeta => const TaskConstMeta(
    debugName: "build_send_tx",
    argNames: [
      "mnemonic",
      "esploraUrl",
      "recipients",
      "feeRateSatKvb",
      "feeAsset",
    ],
  );

  @override
  Future<String> crateApiBuildStakeTx({
    required String mnemonic,
    required String esploraUrl,
    required String stakerPubkey,
    required int csv,
    required BigInt satoshi,
    double? feeRateSatKvb,
    FeeAsset? feeAsset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(stakerPubkey, serializer);
          sse_encode_u_32(csv, serializer);
          sse_encode_u_64(satoshi, serializer);
          sse_encode_opt_box_autoadd_f_32(feeRateSatKvb, serializer);
          sse_encode_opt_box_autoadd_fee_asset(feeAsset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBuildStakeTxConstMeta,
        argValues: [
          mnemonic,
          esploraUrl,
          stakerPubkey,
          csv,
          satoshi,
          feeRateSatKvb,
          feeAsset,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildStakeTxConstMeta => const TaskConstMeta(
    debugName: "build_stake_tx",
    argNames: [
      "mnemonic",
      "esploraUrl",
      "stakerPubkey",
      "csv",
      "satoshi",
      "feeRateSatKvb",
      "feeAsset",
    ],
  );

  @override
  Future<void> crateApiClearWalletCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClearWalletCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearWalletCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_wallet_cache", argNames: []);

  @override
  Future<String> crateApiConfidentialReceiveAddress({
    required String mnemonic,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConfidentialReceiveAddressConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfidentialReceiveAddressConstMeta =>
      const TaskConstMeta(
        debugName: "confidential_receive_address",
        argNames: ["mnemonic"],
      );

  @override
  Future<double> crateApiCpfpSuggestedFeerate({
    required String mnemonic,
    required String esploraUrl,
    required String parentTxid,
    required double targetFeerate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(parentTxid, serializer);
          sse_encode_f_32(targetFeerate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCpfpSuggestedFeerateConstMeta,
        argValues: [mnemonic, esploraUrl, parentTxid, targetFeerate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpfpSuggestedFeerateConstMeta =>
      const TaskConstMeta(
        debugName: "cpfp_suggested_feerate",
        argNames: ["mnemonic", "esploraUrl", "parentTxid", "targetFeerate"],
      );

  @override
  Future<String> crateApiDescriptorFromMnemonic({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDescriptorFromMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDescriptorFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "descriptor_from_mnemonic",
        argNames: ["mnemonic"],
      );

  @override
  Future<String> crateApiFinalizeAndBroadcast({
    required String mnemonic,
    required String esploraUrl,
    required String pset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(pset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFinalizeAndBroadcastConstMeta,
        argValues: [mnemonic, esploraUrl, pset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinalizeAndBroadcastConstMeta =>
      const TaskConstMeta(
        debugName: "finalize_and_broadcast",
        argNames: ["mnemonic", "esploraUrl", "pset"],
      );

  @override
  Future<String> crateApiGenerateMnemonic() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGenerateMnemonicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateMnemonicConstMeta =>
      const TaskConstMeta(debugName: "generate_mnemonic", argNames: []);

  @override
  String crateApiNetworkName() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNameConstMeta =>
      const TaskConstMeta(debugName: "network_name", argNames: []);

  @override
  Future<PsetFee> crateApiPsetFee({required String pset}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pset_fee,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPsetFeeConstMeta,
        argValues: [pset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPsetFeeConstMeta =>
      const TaskConstMeta(debugName: "pset_fee", argNames: ["pset"]);

  @override
  Future<String> crateApiReceiveAddress({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReceiveAddressConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiveAddressConstMeta =>
      const TaskConstMeta(debugName: "receive_address", argNames: ["mnemonic"]);

  @override
  Future<AddressInfo> crateApiReceiveAddressAt({
    required String mnemonic,
    required int index,
    required bool confidential,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_32(index, serializer);
          sse_encode_bool(confidential, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_address_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReceiveAddressAtConstMeta,
        argValues: [mnemonic, index, confidential],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiveAddressAtConstMeta => const TaskConstMeta(
    debugName: "receive_address_at",
    argNames: ["mnemonic", "index", "confidential"],
  );

  @override
  Future<SeqdexSwapRequestOut> crateApiSeqdexBuildSwapRequest({
    required String mnemonic,
    required String esploraUrl,
    required String assetP,
    required BigInt amountP,
    required String assetR,
    required BigInt amountR,
    required String feeAsset,
    required BigInt feeAmount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(assetP, serializer);
          sse_encode_u_64(amountP, serializer);
          sse_encode_String(assetR, serializer);
          sse_encode_u_64(amountR, serializer);
          sse_encode_String(feeAsset, serializer);
          sse_encode_u_64(feeAmount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_seqdex_swap_request_out,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSeqdexBuildSwapRequestConstMeta,
        argValues: [
          mnemonic,
          esploraUrl,
          assetP,
          amountP,
          assetR,
          amountR,
          feeAsset,
          feeAmount,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSeqdexBuildSwapRequestConstMeta =>
      const TaskConstMeta(
        debugName: "seqdex_build_swap_request",
        argNames: [
          "mnemonic",
          "esploraUrl",
          "assetP",
          "amountP",
          "assetR",
          "amountR",
          "feeAsset",
          "feeAmount",
        ],
      );

  @override
  Future<String> crateApiSeqdexSignAccept({
    required String mnemonic,
    required String esploraUrl,
    required String acceptPset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          sse_encode_String(acceptPset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSeqdexSignAcceptConstMeta,
        argValues: [mnemonic, esploraUrl, acceptPset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSeqdexSignAcceptConstMeta => const TaskConstMeta(
    debugName: "seqdex_sign_accept",
    argNames: ["mnemonic", "esploraUrl", "acceptPset"],
  );

  @override
  void crateApiSetAuthHeader({required String value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetAuthHeaderConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetAuthHeaderConstMeta =>
      const TaskConstMeta(debugName: "set_auth_header", argNames: ["value"]);

  @override
  void crateApiSetDataDir({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetDataDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetDataDirConstMeta =>
      const TaskConstMeta(debugName: "set_data_dir", argNames: ["path"]);

  @override
  Future<String> crateApiSignPset({
    required String mnemonic,
    required String pset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(pset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSignPsetConstMeta,
        argValues: [mnemonic, pset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignPsetConstMeta => const TaskConstMeta(
    debugName: "sign_pset",
    argNames: ["mnemonic", "pset"],
  );

  @override
  Future<String> crateApiStakerPublicKey({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStakerPublicKeyConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStakerPublicKeyConstMeta => const TaskConstMeta(
    debugName: "staker_public_key",
    argNames: ["mnemonic"],
  );

  @override
  Future<WalletSync> crateApiSyncWallet({
    required String mnemonic,
    required String esploraUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_sync,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSyncWalletConstMeta,
        argValues: [mnemonic, esploraUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWalletConstMeta => const TaskConstMeta(
    debugName: "sync_wallet",
    argNames: ["mnemonic", "esploraUrl"],
  );

  @override
  Future<void> crateApiValidateAddress({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiValidateAddressConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateAddressConstMeta =>
      const TaskConstMeta(debugName: "validate_address", argNames: ["address"]);

  @override
  Future<void> crateApiValidateMnemonic({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiValidateMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateMnemonicConstMeta => const TaskConstMeta(
    debugName: "validate_mnemonic",
    argNames: ["mnemonic"],
  );

  @override
  Future<List<TxRow>> crateApiWalletTransactions({
    required String mnemonic,
    required String esploraUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(esploraUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tx_row,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWalletTransactionsConstMeta,
        argValues: [mnemonic, esploraUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletTransactionsConstMeta => const TaskConstMeta(
    debugName: "wallet_transactions",
    argNames: ["mnemonic", "esploraUrl"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddressInfo dco_decode_address_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AddressInfo(
      address: dco_decode_String(arr[0]),
      index: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  AssetBalance dco_decode_asset_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AssetBalance(
      assetId: dco_decode_String(arr[0]),
      atoms: dco_decode_String(arr[1]),
    );
  }

  @protected
  AssetDelta dco_decode_asset_delta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AssetDelta(
      assetId: dco_decode_String(arr[0]),
      atoms: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FeeAsset dco_decode_box_autoadd_fee_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fee_asset(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  BtcBalance dco_decode_btc_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BtcBalance(
      balanceSats: dco_decode_String(arr[0]),
      externalNext: dco_decode_u_32(arr[1]),
      changeNext: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  BtcTx dco_decode_btc_tx(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BtcTx(
      hex: dco_decode_String(arr[0]),
      txid: dco_decode_String(arr[1]),
      feeSats: dco_decode_String(arr[2]),
      vsize: dco_decode_u_64(arr[3]),
      inputs: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FeeAsset dco_decode_fee_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FeeAsset(
      assetId: dco_decode_String(arr[0]),
      rate: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  List<AssetBalance> dco_decode_list_asset_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_asset_balance).toList();
  }

  @protected
  List<AssetDelta> dco_decode_list_asset_delta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_asset_delta).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Recipient> dco_decode_list_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_recipient).toList();
  }

  @protected
  List<TxRow> dco_decode_list_tx_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tx_row).toList();
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  FeeAsset? dco_decode_opt_box_autoadd_fee_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_fee_asset(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PsetFee dco_decode_pset_fee(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PsetFee(
      assetId: dco_decode_String(arr[0]),
      atoms: dco_decode_String(arr[1]),
    );
  }

  @protected
  Recipient dco_decode_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Recipient(
      address: dco_decode_String(arr[0]),
      assetId: dco_decode_String(arr[1]),
      satoshi: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  SeqdexSwapRequestOut dco_decode_seqdex_swap_request_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SeqdexSwapRequestOut(
      id: dco_decode_String(arr[0]),
      swapRequestJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  TxRow dco_decode_tx_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TxRow(
      txid: dco_decode_String(arr[0]),
      height: dco_decode_opt_box_autoadd_u_32(arr[1]),
      timestamp: dco_decode_opt_box_autoadd_u_64(arr[2]),
      kind: dco_decode_String(arr[3]),
      fee: dco_decode_u_64(arr[4]),
      deltas: dco_decode_list_asset_delta(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WalletSync dco_decode_wallet_sync(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WalletSync(
      tipHeight: dco_decode_u_32(arr[0]),
      tipHash: dco_decode_String(arr[1]),
      balances: dco_decode_list_asset_balance(arr[2]),
      nextIndex: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddressInfo sse_decode_address_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_index = sse_decode_u_32(deserializer);
    return AddressInfo(address: var_address, index: var_index);
  }

  @protected
  AssetBalance sse_decode_asset_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_assetId = sse_decode_String(deserializer);
    var var_atoms = sse_decode_String(deserializer);
    return AssetBalance(assetId: var_assetId, atoms: var_atoms);
  }

  @protected
  AssetDelta sse_decode_asset_delta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_assetId = sse_decode_String(deserializer);
    var var_atoms = sse_decode_String(deserializer);
    return AssetDelta(assetId: var_assetId, atoms: var_atoms);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  FeeAsset sse_decode_box_autoadd_fee_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fee_asset(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  BtcBalance sse_decode_btc_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_balanceSats = sse_decode_String(deserializer);
    var var_externalNext = sse_decode_u_32(deserializer);
    var var_changeNext = sse_decode_u_32(deserializer);
    return BtcBalance(
      balanceSats: var_balanceSats,
      externalNext: var_externalNext,
      changeNext: var_changeNext,
    );
  }

  @protected
  BtcTx sse_decode_btc_tx(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hex = sse_decode_String(deserializer);
    var var_txid = sse_decode_String(deserializer);
    var var_feeSats = sse_decode_String(deserializer);
    var var_vsize = sse_decode_u_64(deserializer);
    var var_inputs = sse_decode_u_32(deserializer);
    return BtcTx(
      hex: var_hex,
      txid: var_txid,
      feeSats: var_feeSats,
      vsize: var_vsize,
      inputs: var_inputs,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FeeAsset sse_decode_fee_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_assetId = sse_decode_String(deserializer);
    var var_rate = sse_decode_u_64(deserializer);
    return FeeAsset(assetId: var_assetId, rate: var_rate);
  }

  @protected
  List<AssetBalance> sse_decode_list_asset_balance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AssetBalance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_asset_balance(deserializer));
    }
    return ans_;
  }

  @protected
  List<AssetDelta> sse_decode_list_asset_delta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AssetDelta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_asset_delta(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Recipient> sse_decode_list_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Recipient>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recipient(deserializer));
    }
    return ans_;
  }

  @protected
  List<TxRow> sse_decode_list_tx_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TxRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tx_row(deserializer));
    }
    return ans_;
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FeeAsset? sse_decode_opt_box_autoadd_fee_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_fee_asset(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PsetFee sse_decode_pset_fee(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_assetId = sse_decode_String(deserializer);
    var var_atoms = sse_decode_String(deserializer);
    return PsetFee(assetId: var_assetId, atoms: var_atoms);
  }

  @protected
  Recipient sse_decode_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_assetId = sse_decode_String(deserializer);
    var var_satoshi = sse_decode_u_64(deserializer);
    return Recipient(
      address: var_address,
      assetId: var_assetId,
      satoshi: var_satoshi,
    );
  }

  @protected
  SeqdexSwapRequestOut sse_decode_seqdex_swap_request_out(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_swapRequestJson = sse_decode_String(deserializer);
    return SeqdexSwapRequestOut(
      id: var_id,
      swapRequestJson: var_swapRequestJson,
    );
  }

  @protected
  TxRow sse_decode_tx_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_String(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_timestamp = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_fee = sse_decode_u_64(deserializer);
    var var_deltas = sse_decode_list_asset_delta(deserializer);
    return TxRow(
      txid: var_txid,
      height: var_height,
      timestamp: var_timestamp,
      kind: var_kind,
      fee: var_fee,
      deltas: var_deltas,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WalletSync sse_decode_wallet_sync(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tipHeight = sse_decode_u_32(deserializer);
    var var_tipHash = sse_decode_String(deserializer);
    var var_balances = sse_decode_list_asset_balance(deserializer);
    var var_nextIndex = sse_decode_u_32(deserializer);
    return WalletSync(
      tipHeight: var_tipHeight,
      tipHash: var_tipHash,
      balances: var_balances,
      nextIndex: var_nextIndex,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_address_info(AddressInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_u_32(self.index, serializer);
  }

  @protected
  void sse_encode_asset_balance(AssetBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.assetId, serializer);
    sse_encode_String(self.atoms, serializer);
  }

  @protected
  void sse_encode_asset_delta(AssetDelta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.assetId, serializer);
    sse_encode_String(self.atoms, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_fee_asset(
    FeeAsset self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fee_asset(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_btc_balance(BtcBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.balanceSats, serializer);
    sse_encode_u_32(self.externalNext, serializer);
    sse_encode_u_32(self.changeNext, serializer);
  }

  @protected
  void sse_encode_btc_tx(BtcTx self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hex, serializer);
    sse_encode_String(self.txid, serializer);
    sse_encode_String(self.feeSats, serializer);
    sse_encode_u_64(self.vsize, serializer);
    sse_encode_u_32(self.inputs, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fee_asset(FeeAsset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.assetId, serializer);
    sse_encode_u_64(self.rate, serializer);
  }

  @protected
  void sse_encode_list_asset_balance(
    List<AssetBalance> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_asset_balance(item, serializer);
    }
  }

  @protected
  void sse_encode_list_asset_delta(
    List<AssetDelta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_asset_delta(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_recipient(
    List<Recipient> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recipient(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tx_row(List<TxRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tx_row(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_fee_asset(
    FeeAsset? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_fee_asset(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_pset_fee(PsetFee self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.assetId, serializer);
    sse_encode_String(self.atoms, serializer);
  }

  @protected
  void sse_encode_recipient(Recipient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_String(self.assetId, serializer);
    sse_encode_u_64(self.satoshi, serializer);
  }

  @protected
  void sse_encode_seqdex_swap_request_out(
    SeqdexSwapRequestOut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.swapRequestJson, serializer);
  }

  @protected
  void sse_encode_tx_row(TxRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txid, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_u_64(self.timestamp, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_u_64(self.fee, serializer);
    sse_encode_list_asset_delta(self.deltas, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wallet_sync(WalletSync self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.tipHeight, serializer);
    sse_encode_String(self.tipHash, serializer);
    sse_encode_list_asset_balance(self.balances, serializer);
    sse_encode_u_32(self.nextIndex, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
